### ISSUE TITLE
OAuth guild check throws occasional TypeError

### ISSUE THREAD

**Issue by TheShadowEevee** [purduehackers/passport-issuing-office#48]
Discord OAuth seems to occasionally throw out a TypeError when parsing guilds for a user. This is entirely benign but does generate the occasional log error.

Error (Cleaned up):
`JWTSessionError: Read more at https://errors.authjs.dev#jwtsessionerror`
`TypeError: e.find is not a function`
`at [sic]/app/activated/page.js:1:9471`

This is alongside a 401 unauthorized call to https://discordapp.com/api/users/@me/guilds, so it's likely happening on sign out or after a token expires?

**Comment by TheShadowEevee** [comment]
Maybe resolved in #52 
https://github.com/purduehackers/passport-issuing-office/pull/52/commits/61280f23d4f809d153eae0ddb5825d4aaf431880

**Comment by ericswpark** [comment]
Re-open if regressed from #52
